sudo: required
dist: precise
group: edge

language: android

jdk: oraclejdk8

android:
  components:
    - tools
    - build-tools
    - platform-tools

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'


branches:
    only:
        - develop
        - master

script:
    - ./gradlew test
