sudo: required
dist: precise
group: edge

language: android

jdk: oraclejdk8

android:
  components:
    - tools
    - build-tools
    - platform-tools

branches:
    only:
        - develop
        - master

script:
    - ./gradlew test
